## Chat Prefix ##
Prefix: "&5Phoenix Interactive Studios &8&l| "

## Join Messange ##
Join: "&7has joined the game."
JoinSymbol: "&2&l+ "
## Join Messange ##
Quit: "&7has leave the game."
QuitSymbol: "%4%l- "