## Chat Prefix ##
Prefix: "&5Phoenix Interactive Studios &8&l| "

## Join Message ##
Join: "&2&l+  &6%player% &7has joined the game."

## Quit Message ##
Quit: "%4%l- &6%player% &7has leave the game."
